### ISSUE TITLE
13.01.22 Код + черновик пояснительной записки (в файле readme)

### ISSUE THREAD

**Issue by Ysmur** [tortik13/ADDlyaUmnuh#13]
Пояснительная записка - "минипаспорт" проекта (1 - 1,5 страницы), по которому можно быстро понять, что перед нами за проект и кто его авторы. Ориентировочный состав пояснительной записки:
1.	Название проекта
2.	Авторы проекта
3.	Описание идеи (1 абзац)
4.	Описание реализации (1-2 абзаца - основные классы, какие-то интересные приемы, которые были использованы)
**(каждый участник подробно расписывает, за что конкретно отвечает в проекте)** 
5.	Описание технологий + необходимые для запуска библиотеки
6.	1-3 скриншота

**Comment by PinguinCake** [comment]
Моя часть:
1. Стартовое окно
2. Окно паузы
3. Подбор и реализация музыки
4. Выбор режима игры
5. Главный герой и его взаимодействия
6. Препятствия сверху, препятствия снизу
7. Система рекордов + вывод на экран
8. БД и связь с ней
9. Подарки в течение игры

**Comment by tortik13** [comment]
4 пункт:

1. Погода
2. Склейка карт
3. Выбор уровня сложности (скорости)
4. Отвечаю за размер окна и расположение в нём картинок и текста
5. Изображения
6. Монетки
7. Работа музыки

**Comment by tortik13** [comment]
.....................................

..

...
..
.
.
.
...
.......
.
.
..
.
.....
.
..
.
..
.
.
...
..
...
..
.
.....
.
....
.
