### ISSUE TITLE
18.01.22 Почти все готово

### ISSUE THREAD

**Issue by Ysmur** [tortik13/ADDlyaUmnuh#14]
Указать процент выполнения задуманного (по коду). Расписать, что осталось не реализовано.

**Comment by tortik13** [comment]
1. Красота - 10 %
2. Препятствия - 10%
3. Разные скорости - 10 %
4. Дизайны - 10 %
5. Прыжки - 10%
6. Монеты и достижения 10%
7. Удовольствие при игре - 10%
8.  Бонусы для пользователя - 10%
Проект сделан на 80%
---
На ночь перед защитой мы откладываем:
1) Решение мелких ошибок вязанных с координатами - 10%
2) Правки в текст, изменение картинок и музыки - 2%
3) Убирание рабочих и внесение комментариев для просмотра - 2%
Осталось - 12% (много, но что поделаешь)
---
Не реализованные функции:
- смена высоты
- смена фона (?)
- магазин
Это оставшиеся 8%
